### ISSUE TITLE
cant start the app

### ISSUE THREAD

**Issue by ESTEBANMURUZABAL** [nuclearide/nuclear#8]
I am getting this errror:
`
Estebans-MacBook-Pro:nuclear estebanmuruzabal$ yarn dev-start
yarn run v1.7.0
$ concurrently "yarn run build" "yarn start"
$ parcel src/index.html --target electron --public-url .
$ cross-env NODE_ENV=development electron .
[1] 2018-06-21 00:14:30.712 Electron[29791:27169201] *** WARNING: Textured window <AtomNSWindow: 0x7fd17ef29710> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
🚨  /Users/estebanmuruzabal/nuclear/src/js/components/Editor.tsx:35:43: Cannot resolve dependency '../../../lib/tsclient' at '/Users/estebanmuruzabal/nuclear/lib/tsclient'
    at /Users/estebanmuruzabal/nuclear/node_modules/parcel-bundler/lib/Resolver.js:77:19
[0]     at next (native)
[0]     at step (/Users/estebanmuruzabal/nuclear/node_modules/parcel-bundler/lib/Resolver.js:3:191)
[0]     at /Users/estebanmuruzabal/nuclear/node_modules/parcel-bundler/lib/Resolver.js:3:361
`

**Comment by simonhochrein** [comment]
Hello! This project is in active development and is a little unstable. That error looks like you need to check out the submodules. `git submodule init && git submodule update` should fix it.
